version: "3.5"
services:
  api:
    build:
      context: .
    env_file: .env
    ports:
      - "4000:4000"
    restart: unless-stopped
    depends_on:
      - tari
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 3
  tari:
    image: quay.io/krakaw/tari_base_node:latest
    volumes:
      - "$PWD/_data/tari:/root/.tari"
    ports:
      - "18142:18142"
    stdin_open: true
    tty: true
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "$PWD/_data/redis:/data"
    command: "redis-server --appendonly yes"
    environment:
      - REDIS_REPLICATION_MODE=master
